import * as DB from './db.js';
import {createZip,readZip,encodeText,decodeText} from './zip.js';
const $=id=>document.getElementById(id); const $$=sel=>[...document.querySelectorAll(sel)];
let currentView='timeline', selectedPhotos=[], selectedVideo=null, recordedAudio=null, existingMedia=[], removeMediaIds=[], mediaRecorder=null, audioChunks=[], currentMonth=new Date(), memoryTodayEntry=null, deferredPrompt=null;
const labels={gunluk:'Günlük anı',soz:'Komik söz',ilk:'İlk kez',gezi:'Gezi',ozel:'Özel gün',mektup:'Geleceğe mektup'};
const pad=n=>String(n).padStart(2,'0');
const localDT=(d=new Date())=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
const toast=m=>{const d=document.createElement('div');d.className='toast';d.textContent=m;document.body.append(d);setTimeout(()=>d.remove(),2500)};
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fileName=s=>String(s||'dosya').replace(/[^a-z0-9._-]+/gi,'_');
const fmtDate=v=>new Intl.DateTimeFormat('tr-TR',{dateStyle:'long',timeStyle:'short'}).format(new Date(v));
const isLocked=e=>e.type==='mektup'&&e.unlockDate&&new Date(e.unlockDate+'T23:59:59')>new Date();

async function init(){await applyProfile();await applySecurity();bind();await renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');}
function bind(){
 $$('.tabs button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
 ['quickAddBtn','heroAddBtn','emptyAddBtn'].forEach(id=>$(id).onclick=()=>openEntry());
 $('closeDialogBtn').onclick=$('cancelBtn').onclick=()=>closeEntry();
 $('entryType').onchange=()=>{$('unlockDateWrap').hidden=$('entryType').value!=='mektup';saveDraft();};
 ['entryTitle','entryStory','entryQuote','entryPeople','entryActivity','entryPlace','entryMood','entryDate','unlockDate'].forEach(id=>$(id).addEventListener('input',saveDraft));
 $('entryForm').onsubmit=saveEntry;
 $('photoInput').onchange=e=>{selectedPhotos=[...e.target.files].slice(0,8);renderMediaPreview();};
 $('videoInput').onchange=async e=>{const f=e.target.files[0]||null;if(f&&f.size>100*1024*1024){alert('Video 100 MB sınırını aşıyor.');e.target.value='';return;}if(f&&await videoDuration(f)>60){alert('Video 60 saniyeden uzun. Telefonda kırpıp yeniden seç.');e.target.value='';return;}selectedVideo=f;renderMediaPreview();};
 $('recordAudioBtn').onclick=toggleAudioRecord;
 $('getLocationBtn').onclick=getLocation;
 $('searchInput').oninput=renderTimeline;$('typeFilter').onchange=renderTimeline;$('favoriteFilter').onchange=renderTimeline;
 $('prevMonth').onclick=()=>{currentMonth.setMonth(currentMonth.getMonth()-1);renderCalendar();};$('nextMonth').onclick=()=>{currentMonth.setMonth(currentMonth.getMonth()+1);renderCalendar();};
 $('newAlbumBtn').onclick=openAlbum;$('closeAlbumBtn').onclick=()=>$('albumDialog').close();$('albumForm').onsubmit=saveAlbum;
 $('createBookBtn').onclick=createBook;
 $('saveProfileBtn').onclick=saveProfile;$('setPinBtn').onclick=setPin;$('removePinBtn').onclick=removePin;$('unlockBtn').onclick=unlock;$('unlockPin').onkeydown=e=>{if(e.key==='Enter')unlock()};
 $('exportZipBtn').onclick=()=>exportZip('full');$('exportLightZipBtn').onclick=()=>exportZip('light');$('importZipInput').onchange=importZip;$('exportJsonBtn').onclick=exportJson;$('refreshStorageBtn').onclick=renderStorage;$('clearAllBtn').onclick=clearAllData;$('savePrivacyBtn').onclick=savePrivacy;
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').hidden=false;});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').hidden=true;}};
}
function switchView(v){currentView=v;$$('.view').forEach(x=>x.classList.remove('active'));$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$(v+'View').classList.add('active');if(v==='calendar')renderCalendar();if(v==='quotes')renderQuotes();if(v==='firsts')renderFirsts();if(v==='albums')renderAlbums();if(v==='settings')renderSettings();}
async function applyProfile(){const name=await DB.setting('journalName','Küçük Adımlar');$('appTitle').textContent=name;document.title=name;}
async function applySecurity(){const pin=await DB.setting('pinHash','');if(pin)$('lockScreen').hidden=false;}
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function unlock(){const h=await hash($('unlockPin').value);if(h===await DB.setting('pinHash','')){$('lockScreen').hidden=true;$('unlockPin').value='';$('lockError').textContent='';}else $('lockError').textContent='PIN yanlış.';}
async function setPin(){const p=$('pinInput').value.trim();if(!/^\d{4,8}$/.test(p))return alert('PIN 4-8 rakam olmalı.');await DB.setSetting('pinHash',await hash(p));$('pinInput').value='';toast('PIN ayarlandı.');}
async function removePin(){if(confirm('PIN kaldırılsın mı?')){await DB.setSetting('pinHash','');toast('PIN kaldırıldı.');}}

async function openEntry(id=null){resetEntryForm();if(id){const e=await DB.entry(id);if(!e)return;$('editingId').value=id;$('dialogEyebrow').textContent='Kayıt düzenleme';$('dialogTitle').textContent='Anıyı Düzenle';$('entryType').value=e.type;$('entryDate').value=e.date;$('entryTitle').value=e.title||'';$('entryStory').value=e.story||'';$('entryQuote').value=e.quote||'';$('entryPeople').value=(e.people||[]).join(', ');$('entryActivity').value=e.activity||'';$('entryPlace').value=e.place||'';$('entryMood').value=e.mood||'';$('entryLat').value=e.lat||'';$('entryLon').value=e.lon||'';$('entryFavorite').checked=!!e.favorite;$('unlockDate').value=e.unlockDate||'';$('unlockDateWrap').hidden=e.type!=='mektup';existingMedia=await DB.mediaFor(id);renderMediaPreview();}else{const draft=JSON.parse(localStorage.getItem('ka-draft')||'null');$('entryDate').value=localDT();if(draft&&confirm('Kaydedilmemiş taslak bulundu. Açılsın mı?')){for(const [k,v] of Object.entries(draft)){const el=$(k);if(el)el.value=v;}}if(await DB.setting('defaultLocation',false))getLocation();}
 $('entryDialog').showModal();}
function resetEntryForm(){$('entryForm').reset();$('editingId').value='';$('dialogEyebrow').textContent='Yeni kayıt';$('dialogTitle').textContent='Anı Ekle';selectedPhotos=[];selectedVideo=null;recordedAudio=null;existingMedia=[];removeMediaIds=[];$('mediaPreview').innerHTML='';$('locationStatus').textContent='';$('unlockDateWrap').hidden=true;}
function closeEntry(){$('entryDialog').close();}
function saveDraft(){if($('editingId').value)return;const ids=['entryType','entryDate','entryTitle','entryStory','entryQuote','entryPeople','entryActivity','entryPlace','entryMood','unlockDate'];const d={};ids.forEach(id=>d[id]=$(id).value);localStorage.setItem('ka-draft',JSON.stringify(d));}
async function videoDuration(file){return new Promise((res,rej)=>{const v=document.createElement('video');v.preload='metadata';v.onloadedmetadata=()=>{URL.revokeObjectURL(v.src);res(v.duration)};v.onerror=rej;v.src=URL.createObjectURL(file);});}
async function compressImage(file,max=1800,q=.84){const bm=await createImageBitmap(file);const scale=Math.min(1,max/bm.width);const c=document.createElement('canvas');c.width=Math.round(bm.width*scale);c.height=Math.round(bm.height*scale);c.getContext('2d').drawImage(bm,0,0,c.width,c.height);const b=await new Promise(r=>c.toBlob(r,'image/webp',q));bm.close();return b||file;}
async function saveEntry(ev){ev.preventDefault();$('saveEntryBtn').disabled=true;try{const id=$('editingId').value||crypto.randomUUID();const old=$('editingId').value?await DB.entry(id):null;const e={id,type:$('entryType').value,date:$('entryDate').value,title:$('entryTitle').value.trim(),story:$('entryStory').value.trim(),quote:$('entryQuote').value.trim(),people:$('entryPeople').value.split(',').map(x=>x.trim()).filter(Boolean),activity:$('entryActivity').value.trim(),place:$('entryPlace').value.trim(),mood:$('entryMood').value,lat:$('entryLat').value?Number($('entryLat').value):null,lon:$('entryLon').value?Number($('entryLon').value):null,favorite:$('entryFavorite').checked,unlockDate:$('unlockDate').value||null,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};const media=[];for(const f of selectedPhotos){const blob=await compressImage(f);media.push({id:crypto.randomUUID(),entryId:id,kind:'image',name:f.name.replace(/\.[^.]+$/,'.webp'),mime:blob.type,blob});}if(selectedVideo)media.push({id:crypto.randomUUID(),entryId:id,kind:'video',name:selectedVideo.name,mime:selectedVideo.type,blob:selectedVideo});if(recordedAudio)media.push({id:crypto.randomUUID(),entryId:id,kind:'audio',name:`ses-${Date.now()}.webm`,mime:recordedAudio.type,blob:recordedAudio});await DB.putEntry(e,media,removeMediaIds);localStorage.removeItem('ka-draft');closeEntry();await renderAll();toast('Anı kaydedildi.');}catch(err){alert('Kayıt hatası: '+err.message);}finally{$('saveEntryBtn').disabled=false;}}
function renderMediaPreview(){$('mediaPreview').innerHTML='';for(const m of existingMedia){const wrap=document.createElement('div');const el=mediaEl(m);const btn=document.createElement('button');btn.type='button';btn.className='danger';btn.textContent='Kaldır';btn.onclick=()=>{removeMediaIds.push(m.id);existingMedia=existingMedia.filter(x=>x.id!==m.id);renderMediaPreview();};wrap.append(el,btn);$('mediaPreview').append(wrap);}for(const f of selectedPhotos){const i=document.createElement('img');i.src=URL.createObjectURL(f);$('mediaPreview').append(i);}if(selectedVideo){const v=document.createElement('video');v.src=URL.createObjectURL(selectedVideo);v.controls=true;$('mediaPreview').append(v);}if(recordedAudio){const a=document.createElement('audio');a.src=URL.createObjectURL(recordedAudio);a.controls=true;$('mediaPreview').append(a);}}
function mediaEl(m){const u=URL.createObjectURL(m.blob);let el;if(m.kind==='image'){el=document.createElement('img');el.alt=m.name||'Fotoğraf';}else if(m.kind==='video'){el=document.createElement('video');el.controls=true;}else{el=document.createElement('audio');el.controls=true;}el.src=u;return el;}
async function toggleAudioRecord(){if(mediaRecorder?.state==='recording'){mediaRecorder.stop();$('recordAudioBtn').textContent='🎙️ Ses Kaydı';return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});audioChunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>audioChunks.push(e.data);mediaRecorder.onstop=()=>{recordedAudio=new Blob(audioChunks,{type:mediaRecorder.mimeType||'audio/webm'});stream.getTracks().forEach(t=>t.stop());renderMediaPreview();};mediaRecorder.start();$('recordAudioBtn').textContent='⏹️ Kaydı Bitir';}catch(e){alert('Mikrofon açılamadı: '+e.message);}}
function getLocation(){if(!navigator.geolocation)return alert('Konum desteklenmiyor.');$('locationStatus').textContent='Konum alınıyor…';navigator.geolocation.getCurrentPosition(p=>{$('entryLat').value=p.coords.latitude;$('entryLon').value=p.coords.longitude;$('locationStatus').textContent=`${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`;},e=>$('locationStatus').textContent='Konum alınamadı: '+e.message,{enableHighAccuracy:true,timeout:12000});}

async function renderAll(){await renderTimeline();if(currentView==='calendar')await renderCalendar();if(currentView==='quotes')await renderQuotes();if(currentView==='firsts')await renderFirsts();if(currentView==='albums')await renderAlbums();await renderMemoryToday();}
async function renderTimeline(){const all=await DB.entries();const q=$('searchInput').value.toLocaleLowerCase('tr');const type=$('typeFilter').value;const fav=$('favoriteFilter').value;const list=all.filter(e=>(!type||e.type===type)&&(!fav||e.favorite)&&(!q||[e.title,e.story,e.quote,e.place,e.activity,e.mood,...(e.people||[])].join(' ').toLocaleLowerCase('tr').includes(q)));$('timeline').innerHTML='';$('entryCount').textContent=`${list.length} kayıt`;$('emptyState').hidden=!!list.length;for(const e of list)$('timeline').append(await entryCard(e));}
async function entryCard(e){const n=$('entryTemplate').content.firstElementChild.cloneNode(true);n.dataset.id=e.id;n.querySelector('.entry-type').textContent=labels[e.type]||e.type;n.querySelector('.entry-date').textContent=fmtDate(e.date);n.querySelector('.entry-title').textContent=e.title||'Başlıksız anı';const locked=isLocked(e);if(locked){n.querySelector('.entry-story').hidden=true;n.querySelector('.locked-note').hidden=false;n.querySelector('.locked-note').textContent=`🔒 Bu mektup ${new Intl.DateTimeFormat('tr-TR',{dateStyle:'long'}).format(new Date(e.unlockDate))} tarihinde açılacak.`;}else{n.querySelector('.entry-story').textContent=e.story||'';if(e.quote){const q=n.querySelector('.entry-quote');q.hidden=false;q.textContent=`“${e.quote}”`;}}
 const tags=[];(e.people||[]).forEach(x=>tags.push('👤 '+x));if(e.activity)tags.push('🎈 '+e.activity);if(e.place)tags.push('📍 '+e.place);if(e.mood)tags.push('🙂 '+e.mood);if(e.lat&&!await DB.setting('hideCoordinates',true))tags.push(`🧭 ${e.lat.toFixed(4)}, ${e.lon.toFixed(4)}`);for(const t of tags){const s=document.createElement('span');s.className='tag';s.textContent=t;n.querySelector('.entry-tags').append(s);}if(!locked){for(const m of await DB.mediaFor(e.id))n.querySelector('.entry-media').append(mediaEl(m));}
 const f=n.querySelector('.favorite-btn');f.textContent=e.favorite?'★':'☆';f.onclick=async()=>{e.favorite=!e.favorite;e.updatedAt=new Date().toISOString();await DB.putEntry(e);renderAll();};n.querySelector('.edit-btn').onclick=()=>openEntry(e.id);n.querySelector('.delete-btn').onclick=async()=>{if(confirm('Bu anı kalıcı olarak silinsin mi?')){await DB.removeEntry(e.id);renderAll();}};return n;}
async function renderMemoryToday(){const all=await DB.entries(),now=new Date();const found=all.find(e=>{const d=new Date(e.date);return d.getDate()===now.getDate()&&d.getMonth()===now.getMonth()&&d.getFullYear()<now.getFullYear();});$('memoryToday').hidden=!found;if(found){memoryTodayEntry=found;$('memoryTodayTitle').textContent=found.title||'Geçmişten bir anı';$('memoryTodayText').textContent=`${now.getFullYear()-new Date(found.date).getFullYear()} yıl önce bugün`;$('memoryTodayOpen').onclick=()=>{switchView('timeline');document.querySelector(`[data-id="${found.id}"]`)?.scrollIntoView({behavior:'smooth'});};}}
async function renderCalendar(){const all=await DB.entries(),y=currentMonth.getFullYear(),m=currentMonth.getMonth();$('monthLabel').textContent=new Intl.DateTimeFormat('tr-TR',{month:'long',year:'numeric'}).format(currentMonth);const grid=$('calendarGrid');grid.innerHTML='';['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'].forEach(x=>{const d=document.createElement('div');d.className='cal-head';d.textContent=x;grid.append(d);});const first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate();for(let i=0;i<offset;i++){const d=document.createElement('div');d.className='cal-day muted';grid.append(d);}for(let day=1;day<=days;day++){const d=document.createElement('div');d.className='cal-day';d.textContent=day;const dayEntries=all.filter(e=>{const x=new Date(e.date);return x.getFullYear()===y&&x.getMonth()===m&&x.getDate()===day;});if(dayEntries.length){const dot=document.createElement('span');dot.className='cal-dot';d.append(dot);}d.onclick=async()=>{$$('.cal-day').forEach(x=>x.classList.remove('selected'));d.classList.add('selected');$('calendarEntries').innerHTML='';for(const e of dayEntries)$('calendarEntries').append(await entryCard(e));};grid.append(d);}}
async function renderQuotes(){const list=(await DB.entries()).filter(e=>e.quote&&!isLocked(e));$('quoteCount').textContent=`${list.length} söz`;$('quotesList').innerHTML=list.map(e=>`<article class="quote-card card"><time>${safe(fmtDate(e.date))}</time><blockquote>“${safe(e.quote)}”</blockquote><strong>${safe(e.title||'Başlıksız anı')}</strong></article>`).join('');}
async function renderFirsts(){const list=(await DB.entries()).filter(e=>e.type==='ilk');$('firstCount').textContent=`${list.length} ilk`;$('firstsList').innerHTML='';for(const e of list)$('firstsList').append(await entryCard(e));}
async function openAlbum(){$('albumForm').reset();const all=await DB.entries();$('albumEntryChoices').innerHTML=all.map(e=>`<label class="choice-item"><input type="checkbox" value="${e.id}"><span>${safe(new Date(e.date).toLocaleDateString('tr-TR'))} — ${safe(e.title||'Başlıksız')}</span></label>`).join('');$('albumDialog').showModal();}
async function saveAlbum(e){e.preventDefault();await DB.putAlbum({id:crypto.randomUUID(),name:$('albumName').value.trim(),description:$('albumDescription').value.trim(),entryIds:$$('#albumEntryChoices input:checked').map(x=>x.value),createdAt:new Date().toISOString()});$('albumDialog').close();renderAlbums();toast('Albüm oluşturuldu.');}
async function renderAlbums(){const list=await DB.albums();$('albumsList').innerHTML='';for(const a of list){const card=document.createElement('article');card.className='album-card card';card.innerHTML=`<h3>${safe(a.name)}</h3><p>${safe(a.description||'')}</p><small>${a.entryIds.length} anı</small><div class="album-thumbs"></div><button class="danger">Albümü Sil</button>`;for(const id of a.entryIds.slice(0,3)){const m=(await DB.mediaFor(id)).find(x=>x.kind==='image');if(m){const i=document.createElement('img');i.src=URL.createObjectURL(m.blob);card.querySelector('.album-thumbs').append(i);}}card.querySelector('.danger').onclick=async()=>{if(confirm('Albüm silinsin mi?')){await DB.deleteAlbum(a.id);renderAlbums();}};$('albumsList').append(card);}}
async function createBook(){let list=await DB.entries();const s=$('bookStart').value,e=$('bookEnd').value;if(s)list=list.filter(x=>x.date.slice(0,10)>=s);if(e)list=list.filter(x=>x.date.slice(0,10)<=e);if($('bookFavorites').checked)list=list.filter(x=>x.favorite);list=list.filter(x=>!isLocked(x));const parts=[];for(const x of [...list].reverse()){const media=await DB.mediaFor(x.id);const imgs=[];for(const m of media.filter(y=>y.kind==='image').slice(0,4)){imgs.push(`<img src="${await blobDataURL(m.blob)}">`);}parts.push(`<article><h2>${safe(x.title||'Başlıksız anı')}</h2><time>${safe(fmtDate(x.date))}</time><p>${safe(x.story||'').replace(/\n/g,'<br>')}</p>${x.quote?`<blockquote>“${safe(x.quote)}”</blockquote>`:''}<div class="imgs">${imgs.join('')}</div></article>`);}const w=window.open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${safe($('bookTitle').value)}</title><style>body{font-family:Georgia,serif;max-width:900px;margin:auto;padding:40px;color:#33252d}h1{text-align:center;font-size:38px}article{page-break-inside:avoid;border-bottom:1px solid #ddd;padding:24px 0}time{color:#777}blockquote{background:#fff3d4;padding:14px;border-left:4px solid #c99b36}.imgs{display:grid;grid-template-columns:1fr 1fr;gap:8px}.imgs img{width:100%;max-height:440px;object-fit:cover}@media print{button{display:none}}</style></head><body><h1>${safe($('bookTitle').value)}</h1>${parts.join('')}<button onclick="print()">PDF / Yazdır</button></body></html>`);w.document.close();}
function blobDataURL(b){return new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(b);});}

async function sha256Hex(bytes){const b=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);const h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function backupBaseName(kind='full',prefix='kucuk-adimlar'){const day=new Date().toISOString().slice(0,10);const stamp=new Date().toTimeString().slice(0,5).replace(':','');return `${prefix}-${kind}-yedek-${day}-${stamp}.zip`;}
async function buildBackup(kind='full'){
 const es=await DB.entries(), all=await DB.allMedia(), as=await DB.albums(), ss=await DB.allSettings();
 const ms=kind==='light'?all.filter(m=>m.kind!=='video'):all;
 const media=[];const files=[];
 for(const m of ms){const bytes=new Uint8Array(await m.blob.arrayBuffer());const path=`media/${m.id}-${fileName(m.name)}`;media.push({id:m.id,entryId:m.entryId,kind:m.kind,name:m.name,mime:m.mime,size:bytes.length,path,sha256:await sha256Hex(bytes)});files.push({name:path,data:bytes});}
 const counts={entries:es.length,media:media.length,photos:media.filter(x=>x.kind==='image').length,videos:media.filter(x=>x.kind==='video').length,audio:media.filter(x=>x.kind==='audio').length,albums:as.length};
 const manifest={app:'Küçük Adımlar',format:'kucuk-adimlar-backup',backupVersion:4,kind,createdAt:new Date().toISOString(),counts,includes:{entries:true,photos:true,videos:kind==='full',audio:true,albums:true,settings:true},entries:es,albums:as,settings:ss,media};
 files.unshift({name:'manifest.json',data:encodeText(JSON.stringify(manifest,null,2))});
 return {blob:await createZip(files),manifest};
}
async function shareOrDownload(blob,name){
 const file=new File([blob],name,{type:'application/zip'});
 if(navigator.canShare?.({files:[file]})){try{await navigator.share({title:'Küçük Adımlar Yedeği',text:'Küçük Adımlar günlük yedeği',files:[file]});return 'shared';}catch(e){if(e.name!=='AbortError')console.warn(e);}}
 download(blob,name);return 'downloaded';
}
async function exportZip(kind='full'){
 const btn=kind==='full'?$('exportZipBtn'):$('exportLightZipBtn');btn.disabled=true;const old=btn.textContent;btn.textContent='Yedek hazırlanıyor…';
 try{const {blob,manifest}=await buildBackup(kind);const name=backupBaseName(kind);await shareOrDownload(blob,name);await DB.setSetting('lastBackupAt',manifest.createdAt);await DB.setSetting('lastBackupKind',kind);await DB.setSetting('lastBackupEntryCount',manifest.counts.entries);await renderBackupStatus();toast(kind==='full'?'Tam yedek hazır.':'Hafif yedek hazır.');}
 catch(e){alert('Yedek oluşturulamadı: '+e.message);}finally{btn.disabled=false;btn.textContent=old;}
}
async function validateBackup(files){
 const raw=files.get('manifest.json')||files.get('backup.json');if(!raw)throw new Error('manifest.json bulunamadı.');
 const data=JSON.parse(decodeText(raw));if(data.app!=='Küçük Adımlar')throw new Error('Bu dosya Küçük Adımlar yedeği değil.');
 if(!Array.isArray(data.entries)||!Array.isArray(data.media))throw new Error('Yedek yapısı eksik veya bozuk.');
 let missing=0,corrupt=0;
 for(const m of data.media){const bytes=files.get(m.path);if(!bytes){missing++;continue;}if(m.sha256&&await sha256Hex(bytes)!==m.sha256)corrupt++;}
 if(missing||corrupt)throw new Error(`Medya doğrulaması başarısız. Eksik: ${missing}, bozuk: ${corrupt}.`);
 return data;
}
function chooseRestoreMode(data){
 const summary=`Yedek: ${new Date(data.createdAt||Date.now()).toLocaleString('tr-TR')}\nKayıt: ${data.entries.length}\nFotoğraf: ${(data.media||[]).filter(x=>x.kind==='image').length}\nVideo: ${(data.media||[]).filter(x=>x.kind==='video').length}\nSes: ${(data.media||[]).filter(x=>x.kind==='audio').length}\n\nTamamen değiştirmek için TAMAM, birleştirme seçenekleri için İPTAL.`;
 if(confirm(summary))return 'replace';
 const merge=prompt('Geri yükleme modu:\n1 = Birleştir (daha yeni kayıt kazanır)\n2 = Yalnızca eksikleri ekle\n0 = Vazgeç','1');
 return merge==='1'?'merge':merge==='2'?'missing':'cancel';
}
async function safetyBackupBeforeRestore(){
 const count=(await DB.entries()).length;if(!count)return;
 const {blob}=await buildBackup('full');download(blob,backupBaseName('guvenlik','geri-yukleme-oncesi'));
 await DB.setSetting('lastSafetyBackupAt',new Date().toISOString());
}
async function importZip(ev){
 const f=ev.target.files[0];if(!f)return;
 try{$('backupStatus').textContent='Yedek doğrulanıyor…';const files=await readZip(f),data=await validateBackup(files);const mode=chooseRestoreMode(data);if(mode==='cancel')return;
 if(mode==='replace'){await safetyBackupBeforeRestore();if(!confirm('Güvenlik yedeği indirildi. Mevcut veriler tamamen silinip seçilen yedek yüklensin mi?'))return;await DB.clearAll();}
 for(const [k,v] of Object.entries(data.settings||{})){if(k==='pinHash'&&mode!=='replace')continue;await DB.setSetting(k,v);}
 for(const a of data.albums||[])await DB.putAlbum(a);
 const current=new Map((await DB.entries()).map(e=>[e.id,e]));let added=0,updated=0,skipped=0;
 for(const e of data.entries||[]){const old=current.get(e.id);if(mode==='missing'&&old){skipped++;continue;}if(mode==='merge'&&old&&new Date(old.updatedAt||old.date)>=new Date(e.updatedAt||e.date)){skipped++;continue;}
  const media=[];for(const mm of (data.media||[]).filter(x=>x.entryId===e.id)){const bytes=files.get(mm.path);if(bytes)media.push({id:mm.id,entryId:mm.entryId,kind:mm.kind,name:mm.name,mime:mm.mime,blob:new Blob([bytes],{type:mm.mime})});}
  const oldMedia=old?await DB.mediaFor(e.id):[];await DB.putEntry(e,media,oldMedia.map(x=>x.id));old?updated++:added++;
 }
 await DB.setSetting('lastRestoreAt',new Date().toISOString());await applyProfile();await renderAll();await renderBackupStatus();alert(`Geri yükleme tamamlandı.\nEklenen: ${added}\nGüncellenen: ${updated}\nAtlanan: ${skipped}`);
 }catch(e){alert('ZIP geri yüklenemedi: '+e.message);}finally{ev.target.value='';await renderBackupStatus();}
}
async function exportJson(){const payload={app:'Küçük Adımlar',format:'kucuk-adimlar-text-backup',backupVersion:4,exportedAt:new Date().toISOString(),entries:await DB.entries(),albums:await DB.albums(),settings:await DB.allSettings()};download(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),`kucuk-adimlar-metin-${new Date().toISOString().slice(0,10)}.json`);}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
async function renderBackupStatus(){
 const at=await DB.setting('lastBackupAt','');const kind=await DB.setting('lastBackupKind','');const oldCount=Number(await DB.setting('lastBackupEntryCount',0));const count=(await DB.entries()).length;const status=$('backupStatus'),warn=$('backupWarning');
 if(!at){status.textContent=`Henüz tam yedek alınmadı. Günlükte ${count} kayıt var.`;warn.hidden=count===0;warn.textContent='⚠ İlk tam yedeğini al ve dosyayı Google Drive gibi ikinci bir yerde sakla.';return;}
 const days=Math.floor((Date.now()-new Date(at).getTime())/86400000),newItems=Math.max(0,count-oldCount);status.innerHTML=`Son yedek: <strong>${new Date(at).toLocaleString('tr-TR')}</strong><br>Tür: ${kind==='full'?'Tam ZIP':'Hafif ZIP'} · Son yedekten sonra ${newItems} yeni kayıt`;
 warn.hidden=days<7&&newItems<10;if(!warn.hidden)warn.textContent=`⚠ ${days} gündür tam yedek yenilenmedi veya ${newItems} yeni anı eklendi.`;
}
async function renderSettings(){await renderBackupStatus();$('childName').value=await DB.setting('childName','');$('childBirth').value=await DB.setting('childBirth','');$('journalName').value=await DB.setting('journalName','Küçük Adımlar');$('defaultLocation').checked=await DB.setting('defaultLocation',false);$('hideCoordinates').checked=await DB.setting('hideCoordinates',true);renderStorage();}
async function saveProfile(){await DB.setSetting('childName',$('childName').value.trim());await DB.setSetting('childBirth',$('childBirth').value);await DB.setSetting('journalName',$('journalName').value.trim()||'Küçük Adımlar');await applyProfile();toast('Profil kaydedildi.');}
async function savePrivacy(){await DB.setSetting('defaultLocation',$('defaultLocation').checked);await DB.setSetting('hideCoordinates',$('hideCoordinates').checked);toast('Gizlilik ayarları kaydedildi.');}
async function renderStorage(){let text='Tarayıcı depolama bilgisi desteklenmiyor.';if(navigator.storage?.estimate){const x=await navigator.storage.estimate();const mb=n=>(n/1024/1024).toFixed(1);text=`Kullanılan: ${mb(x.usage||0)} MB / Kota: ${mb(x.quota||0)} MB`;}$('storageInfo').textContent=text;}
async function clearAllData(){if(confirm('Tüm anılar, medya ve albümler kalıcı olarak silinecek. Emin misin?')&&confirm('Bu işlem geri alınamaz. Son kez onaylıyor musun?')){await DB.clearAll();await renderAll();toast('Tüm günlük verileri silindi.');}}
init();
